version: '3.4'

services:
  db:
    image: postgres:15
    container_name: pgdb
    environment:
      POSTGRES_DB: co2db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data.csv:/docker-entrypoint-initdb.d/data.csv
      - ./db/cube.csv:/docker-entrypoint-initdb.d/cube.csv
      - ./db/shape.sql:/docker-entrypoint-initdb.d/shape.sql


  ontop:
    image: ontop/ontop
    environment:
      #ONTOP_ONTOLOGY_FILE: /opt/ontop/input/co2db.cube.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/co2db.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/co2db.compose.properties
      #ONTOP_PORTAL_FILE: /opt/ontop/input/university-complete.portal.toml
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
      ONTOP_LAZY_INIT: "true"
    volumes:
      - ./input:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
